### ISSUE TITLE
是否支持类似clishe一样，进入子命令的上下文

### ISSUE THREAD

**Issue by RickSKy** [jiashiwen/interactcli-rs#1]
命令行交互式程序，可能有进入子命令的context，在子命令模式下，有一批可以使用的子命令；有点类似交换机那种
```bash
[XXXX] interface ethernet 0/0/0
[Switch- ethernet 0/0/0] speed 10
[Switch- ethernet 0/0/0] duplex full
```
interface ethernet 0/0/0 输入之后，可以方便地定义子命令形式，只允许 speed [10/100/1000] 或 duplex [full half] 的形式

**Comment by jiashiwen** [comment]
我理解 比如子命令 A 下面有C 和 D，B下面有E和F，假设A和B在同一级那么当你使用子命令A 的是好 按tab键只显示C和D。这种方式是支持的
